; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
upload_port = SET_PORT
monitor_port = SET_PORT
monitor_speed = 115200

framework = arduino
build_unflags =
  -std=c11
  -std=gnu11
  -std=c++11
  -std=gnu++11
  -Os
  -O1
  -O2
  -O3
build_flags =
  -std=gnu17
  -std=gnu++17
lib_deps = adafruit/Adafruit PN532@^1.3.4

[common-debug]
build_flags =
  ${common.build_flags}
  -O0
  -g3
  -DDEBUG
  -DCORE_DEBUG_LEVEL=5

[common-release]
build_flags =
  ${common.build_flags}
  -DNDEBUG

[common-ESP8266]
platform = espressif8266@4.2.1
board = nodemcuv2

[common-ESP32]
platform = espressif32@6.12.0
board = esp32doit-devkit-v1

[env]
check_tool = clangtidy
debug_tool = esp-prog
debug_init_break = tbreak setup

lib_ldf_mode = chain
lib_compat_mode = off

upload_protocol = esptool
upload_port = ${common.upload_port}
monitor_port = ${common.monitor_port}
monitor_speed = ${common.monitor_speed}

[env:ESP8266-Debug]
platform = ${common-ESP8266.platform}
board = ${common-ESP8266.board}
framework = ${common.framework}
build_type = debug
build_unflags = ${common.build_unflags}
build_flags = ${common-debug.build_flags}
lib_deps = ${common.lib_deps}

[env:ESP8266-Release]
platform = ${common-ESP8266.platform}
board = ${common-ESP8266.board}
framework = ${common.framework}
build_type = release
build_unflags = ${common.build_unflags}
build_flags = ${common-release.build_flags}
lib_deps = ${common.lib_deps}